### ISSUE TITLE
Wiki permissions?

### ISSUE THREAD

**Issue by kyle-rader** [janko/rodauth-rails#125]
Out of curiosity, I noticed on the Wiki that I could edit and add pages. ([example page](jankomarohnic)). If this is intentional, then please ignore, but you may want to review the Wiki permissions settings.

**Comment by janko** [comment]
Yes, this is intentional. There aren't any fine-grained wiki permissions as far as I know, either everything is publicly editable or nothing is.

<img width="808" alt="Screenshot 2022-07-10 at 21 13 30" src="https://user-images.githubusercontent.com/795488/178158777-b141cac4-c342-415d-a4e7-e3665648fd45.png">

**Comment by janko** [comment]
@kyle-rader Could I kindly ask you to then remove the test wiki page?

**Comment by kyle-rader** [comment]
Done!
