### ISSUE TITLE
Rodauth Invitation Question

### ISSUE THREAD

**Issue by dpaluy** [janko/rodauth-rails#192]
👋,
I'm moving from Devise to Rodauth and one important functionality I'm missing is Invitation flow.

Is there an alternative to [Devise Invitable](https://github.com/scambra/devise_invitable)?

If not, what's the correct way to implement it?
Should it be a part of the `rodauth-rails` extension?

Thank you!

**Comment by janko** [comment]
There isn't any equivalent in Rodauth AFAIK, it would be great if someone would built it. It would definitely be best as a separate gem, and it can be implemented just in Rodauth (I see no reason it should depend on Rails).

I will close this, since Issues are only for bug reports, while questions should be asked in Discussions.
