### ISSUE TITLE
Disable User Creation

### ISSUE THREAD

**Issue by delCatta** [janko/rodauth-rails#86]
I would like to know how I can disable Account Creation. 

I need this because I have one admin account that could create accounts.

Removing `:create_account`  from the `enable` in `rodauth_main.rb` doen't seem to work...

**Comment by janko** [comment]
You'll need to disable verify_account and verify_account_grace_period too, as those depend on the create_account feature, so they pull it in automatically.

**Comment by brunoprietog** [comment]
Isn't there a way to disable some routes? For example, make /create-account path not available. If you disable the feature, you cannot use it with internal_request in other parts of the application

**Comment by brunoprietog** [comment]
I discovered that you can set the value of a rodauth route configuration to nil, for example:

`create_account_route nil`

This causes the rodauth router to ignore it and pass it to the Rails router, allowing you to easily handle the error

**Comment by janko** [comment]
@brunoprietog I thought I knew everything there is to know about Rodauth, but you just taught me something new 🙂 This works because, when `nil` is passed to [`r.is`](https://github.com/jeremyevans/rodauth/blob/c560e715df54201a9f4b2c36290989ba33f06999/lib/rodauth.rb#L138), it [doesn't match](https://github.com/jeremyevans/roda#false-nil-). BTW, I think showing this would be a useful addition to the [Change route path](http://rodauth.jeremyevans.net/rdoc/files/doc/guides/paths_rdoc.html) official guide 😉 

@delCatta Since the question was answered, I'm closing this one. In the future please use GitHub Discussions for usage questions 🙂
